name: scrollanimation
description: "A Flutter package for creating scroll-based animations"
version: 0.0.1
homepage: https://github.com/NIKET898/Scrolling-Animation.git

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
